function dataStruct = extractStruct(erddapStruct,dtype)
dataStruct=struct('dtypename',erddapStruct(dtype,1).dtypename,'datasetname',erddapStruct(dtype,1).datasetname,'longname',erddapStruct(dtype,1).longname,...
            'varname',erddapStruct(dtype,1).varname,'hasAlt',erddapStruct(dtype,1).hasAlt(dtype),'latSouth',erddapStruct(dtype,1).latSouth(dtype),'lon360',erddapStruct(dtype,1).lon360(dtype),...
            'minLongitude',erddapStruct(dtype,1).minLongitude(dtype),'maxLongitude',erddapStruct(dtype,1).maxLongitude(dtype),'longitudeSpacing',erddapStruct(dtype,1).longitudeSpacing(dtype),...
            'minLatitude',erddapStruct(dtype,1).minLatitude(dtype),'maxLatitude',erddapStruct(dtype,1).maxLatitude(dtype),'latitudeSpacing',erddapStruct(dtype,1).latitudeSpacing(dtype),...
            'minAltitude',erddapStruct(dtype,1).minAltitude,'maxAltitude',erddapStruct(dtype,1).maxAltitude,...
            'minTime',erddapStruct(dtype,1).minTime(dtype),'maxTime',erddapStruct(dtype,1).maxTime(dtype),'timeSpacing',erddapStruct(dtype,1).timeSpacing(dtype),'infoUrl',erddapStruct(dtype,1).infoUrl(dtype));
